"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 room-4.glb
*/

import { useGLTF, useTexture } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import React, { useRef } from "react";
import * as THREE from "three";

type GLTFResult = {
  nodes: { [name: string]: THREE.Mesh };
  materials: { [name: string]: THREE.Material };
};

const Room_4: React.FC<React.ComponentProps<"group">> = (props) => {
  const { nodes } = useGLTF("/models/room-4.glb") as unknown as GLTFResult;

  const bakedTexture = useTexture("/textures/room-4.jpg", (loader) => {
    loader.flipY = false; // ✅ set flipY while loading
  });

  // 🕒 Clock refs
  const hoursRef = useRef<THREE.Mesh>(null);
  const minutesRef = useRef<THREE.Mesh>(null);
  const secondsRef = useRef<THREE.Mesh>(null);

  // ⏱ Animate clock hands
  useFrame(() => {
    const date = new Date();
    const h = date.getHours() % 12;
    const m = date.getMinutes();
    const s = date.getSeconds() + date.getMilliseconds() / 1000;

    if (hoursRef.current)
      hoursRef.current.rotation.x = -((h + m / 60) * (Math.PI / 6));
    if (minutesRef.current)
      minutesRef.current.rotation.x = -((m + s / 60) * (Math.PI / 30));
    if (secondsRef.current)
      secondsRef.current.rotation.x = -(s * (Math.PI / 30));
  });

  // 🖼 Photos for hover outlines
  const photos = ["photo-1", "photo-2", "photo-3", "photo-4", "photo-5"];

  return (
    <group {...props} dispose={null}>
      {/* 🧱 Wall */}
      {nodes.wall && (
        <mesh geometry={nodes.wall.geometry} position={[0.497, 2.987, -1.864]}>
          <meshBasicMaterial map={bakedTexture} />
        </mesh>
      )}

      {/* 🕰 Clock */}
      {nodes.Clock && (
        <group
          position={[-3.966, 3.98, -1.421]}
          rotation={[0, -0.77, 0]}
          scale={1.224}
        >
          <mesh geometry={nodes.Clock.geometry}>
            <meshBasicMaterial map={bakedTexture} />
          </mesh>
          {nodes.hours && (
            <mesh ref={hoursRef} geometry={nodes.hours.geometry}>
              <meshBasicMaterial map={bakedTexture} />
            </mesh>
          )}
          {nodes.minutes && (
            <mesh ref={minutesRef} geometry={nodes.minutes.geometry}>
              <meshBasicMaterial map={bakedTexture} />
            </mesh>
          )}
          {nodes.secondes && (
            <mesh ref={secondsRef} geometry={nodes.secondes.geometry}>
              <meshBasicMaterial map={bakedTexture} />
            </mesh>
          )}
        </group>
      )}

      {/* ☕ Schrödinger Mug */}
      {nodes.schrodinger && (
        <mesh
          geometry={nodes.schrodinger.geometry}
          position={[-0.299, 1.898, 2.997]}
          rotation={[0, -0.469, 0]}
        >
          <meshBasicMaterial map={bakedTexture} />
        </mesh>
      )}

      {/* 💨 Coffee Smoke */}
      {nodes["coffe-smoke"] && (
        <mesh
          name="coffe-smoke"
          geometry={nodes["coffe-smoke"].geometry}
          position={[-0.312, 1.972, 2.997]}
          rotation={[0, -0.486, 0]}
        >
          <meshBasicMaterial map={bakedTexture} transparent opacity={0.5} />
        </mesh>
      )}

      {/* 🪞 Table Plane */}
      {nodes.Plane015 && (
        <mesh
          geometry={nodes.Plane015.geometry}
          position={[-0.588, 1.826, 2.993]}
        >
          <meshBasicMaterial map={bakedTexture} />
        </mesh>
      )}

      {/* 🖼 Photo frames with hover outlines */}
      {photos.map((name) => {
        const node = nodes[name];
        if (!node) return null;

        return (
          <mesh
            key={name}
            geometry={node.geometry}
            position={node.position}
            rotation={node.rotation}
          >
            <meshBasicMaterial map={bakedTexture} />
          </mesh>
        );
      })}
    </group>
  );
};

// 🔹 Preload GLB
useGLTF.preload("/models/room-4.glb");

export default Room_4;
